### ISSUE TITLE
Conversion of Powerpoint to Markdown

### ISSUE THREAD

**Issue by ramlaxman** [gwillz/slides#3]
This is some big fish task. 

I hit by this idea after giving thought if I am presenting to students: 
  - with 30 to 40 slides of a PPT file without having my own laptop;
  - not a specific version of Office (PPT slightly changes in terms of animation and spacing 
    as office version changes);
  - What if powerpoint starts crashing suddenly by God's act?

You can extend this idea by using some of these:

1. [pandoc](https://pandoc.org/)
2. [pptx2md](https://github.com/revan/pptx2md) this one is incomplete.

**Comment by gwillz** [comment]
Yeah this is way out of scope for this project.

If you're looking for a PPT slides viewer, both Google Drive and Dropbox have adequate online solutions.

This project simply tackles making Markdown a suitable presentation format, not so much about achieving feature-parity with PPT or performing file conversions.

I'd imagine this to instead be an API or service that converts pptx files into markdown files that are readable by the slides app. Sure the two can integrate, but this isn't something that can be solved here.
