### ISSUE TITLE
404 after forking

### ISSUE THREAD

**Issue by ramlaxman** [gwillz/slides#4]
I tried to fork on github also enabled github pages but I am getting 404 error.

When appending with index.html, I am getting readme page.

![image](https://user-images.githubusercontent.com/1982225/52185254-83c29c80-2843-11e9-8909-987547f1c4a1.png)

What I am doing wrong? Please let me know.

**Comment by gwillz** [comment]
If you set up github pages with the 'master' branch, it will auto-render the `readme.md` file.

You'll see in the `package.json` there is a 'pages' script to deploy the _application_ to github pages. This just pushes the 'public' folder to the 'gh-pages' branch. You may need to update the settings in github to use the 'gh-pages' branch.

Full process:

```sh
# install dependencies
npm install
# build the applications
NODE_ENV=production npm run webpack
# deploy to gh-pages
npm run pages
```

**Comment by ramlaxman** [comment]
Solved. Thanks
